const stories = [
  {
    title: "TRẦM LUÂN TRONG VÒNG LẶP: KHÔN TRẠCH CỦA BẠO QUÂN",
    img: "https://i.ibb.co/PZvH2SFY/221eb754d33b616b0dca199530c42205.png",
    desc: "Ngôn tình - cổ đại - H+",
    tags: ["ngontinh", "codai", "H+"],
    link: "truyen/khon-trach-cua-bao-quan.html"
  },

  {
    title: "TUYẾT TRUNG CHIÊU – TRƯỜNG AN NHẤT MỘNG",
    img: "https://i.ibb.co/1YdPV645/e39b-b76603eb1269841959874ec6efb3da9b.jpg",
    desc: "Ngôn tình - cổ đại",
    tags: ["ngontinh", "codai"],
    link: "truyen/tuyet-trung-chieu-truong-an-nhat-mong.html"
  },

  {
    title: "TEST",
    img: "https://i.ibb.co/1YdPV645/e39b-b76603eb1269841959874ec6efb3da9b.jpg",
    desc: "Ngôn tình - cổ đại",
    tags: ["ngontinh", "codai"],
    link: "truyen/test.html"
  },

  {
    title: "XUYÊN KHÔNG LÀM HOÀNG HẬU",
    img: "https://picsum.photos/300/180?random=2",
    desc: "Xuyên không - cổ đại",
    tags: ["xuyenkhong", "codai"],
    link: "truyen/test.html"
  },

  {
    title: "TỔNG TÀI SỦNG VỢ",
    img: "https://picsum.photos/300/180?random=3",
    desc: "Hiện đại - sủng",
    tags: ["hiendai", "ngontinh"],
    link: "truyen/test.html"
  },

  {
    title: "TRỌNG SINH BÁO THÙ",
    img: "https://picsum.photos/300/180?random=4",
    desc: "Trọng sinh - ngược",
    tags: ["trongsinh", "nguoc"],
    link: "truyen/test.html"
  }
];
