const stories = [
{
  title: "Khôn Trạch Của Bạo Quân",
  tags: ["ngontinh","codai","H+"],
  link: "truyen/khon-trach-cua-bao-quan.html",
  img: "images/bia1.jpg",
  desc: "Ngôn tình cổ đại H+, cực ngược, cực cuốn"
},
{
  title: "Tuyết Trung Chiêu – Trường An Nhất Mộng",
  tags: ["ngontinh","codai"],
  link: "truyen/tuyet-trung-chieu-truong-an-nhat-mong.html",
  img: "images/bia2.jpg",
  desc: "Truyện cổ đại nhẹ nhàng, sâu sắc"
},
{
  title: "Test",
  tags: ["ngontinh","codai"],
  link: "truyen/test.html",
  img: "images/bia2.jpg",
  desc: "Truyện test demo"
}
];
