const stories = [
{
  title: "Hiện Đại",
  tag: ["tongtai","sung","ngontinh"],
  link: "https://storyxxx.github.io/truyen-web/truyen1.html"
},
{
  title: "Cổ Đại",
  tag: ["xuyenkhong","nguoc","codai"],
  link: "https://storyxxx.github.io/truyen-web/truyen1.html"
},
{
  title: "Dân quốc",
  tag: ["tongtai","nguoc"],
  link: "https://storyxxx.github.io/truyen-web/truyen1.html"
},
{
  title: "H văn",
  tag: ["H+"],
  link: "https://storyxxx.github.io/truyen-web/truyen1.html"
}
];
